name: sota_caballo_rey
description: "A new Flutter project."

publish_to: 'none' # No publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # Para las fuentes de google
  web_socket_channel: ^2.4.0

  # Paquete para cargar el video de la pantalla de carga.
  video_player: ^2.5.5

  # Paquete para almacenar tokens de forma segura.
  flutter_secure_storage: ^9.2.4

  # Paquete para realizar peticiones HTTP
  http: ^1.3.0

  # Paquete para añadir carrusel de imagenes
  carousel_slider: ^5.0.0

  # Paquete para transiciones más suaves.
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  # Lints recomendadas para seguir el estilo de flutter.
  flutter_lints: ^5.0.0


flutter:

  # Para poder usar todo lo proporcionado por material design
  uses-material-design: true

  # Ruta a la carpeta con las imagenes a usar
  assets:
    - assets/images/
    - assets/images/cards/
    - assets/json/config.json
    
  # Fuentes usadas
  fonts:
    - family: tituloApp
      fonts:
        - asset: assets/fonts/GlossypersonaluseRegular-eZL93.otf
